### ISSUE TITLE
broken on 1.6.0

### ISSUE THREAD

**Issue by RazaGR** [Scholar01/sd-webui-mov2mov#83]
[broken on 1.6.0 new release](https://github.com/AUTOMATIC1111/stable-diffusion-webui)
```

 Error loading script: m2m_ui.py
    Traceback (most recent call last):
      File "/usr/local/var/apps/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/usr/local/var/apps/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/usr/local/var/apps/stable-diffusion-webui/extensions/sd-webui-mov2mov/scripts/m2m_ui.py", line 12, in <module>
        from modules.ui import paste_symbol, clear_prompt_symbol, extra_networks_symbol, apply_style_symbol, save_style_symbol, \
    ImportError: cannot import name 'create_seed_inputs' from 'modules.ui' (/usr/local/var/apps/stable-diffusion-webui/modules/ui.py)
```

**Comment by tmode-1960** [comment]
same error here

**Comment by lafintiger** [comment]
Same here.

**Comment by tiola** [comment]
Same here

**Comment by C4l1b3r** [comment]
i see i dont need to respond.  same error here

**Comment by cyberdenz** [comment]
works on 1.5.2
error appears starting 1.6.0-RC

**Comment by C4l1b3r** [comment]
> Same issue here. Is it easy to roll back to a previous version of Automatic1111? This latest version seems to have broken a lot of things..

Yeah just edit the webui-user.bat and add a line 
git checkout v1.5.2
Save and launch

**Comment by calonye** [comment]
Same here.

**Comment by lounice** [comment]
same here

**Comment by calonye** [comment]
> Until the original creator fixes these issues, try this fork https://github.com/DavG25/sd-webui-mov2mov works great for me,

menu not working

**Comment by C4l1b3r** [comment]
I'll stay on 1.5 I know it works,

**Comment by Scholar01** [comment]
I will fix it later

**Comment by Scholar01** [comment]
fixed it
